openapi: 3.0.3
info:
  description: Open api for dropwizard test project
  title: Dropwizard API learning Application
  version: 1.0.0
servers:
- url: localhost:8080
tags:
- description: person controller
  name: person
paths:
  /persons:
    post:
      description: new Person
      operationId: createPerson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePerson'
        description: A payload for creating a new Person
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadPerson'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Validation Exception.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Unauthorized.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: You do not have permission to perform this action.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Conflict with current state of the resource.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Something went wrong.
      summary: Create new Persons
      tags:
      - person
      x-contentType: application/json
      x-accepts: application/json
      x-tags:
      - tag: person
components:
  responses:
    NoContentResponse:
      description: The request was succesfully processed.
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
      description: Validation Exception.
    Unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
      description: Unauthorized.
    Forbidden:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
      description: You do not have permission to perform this action.
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
      description: The specified resource was not found.
    Conflict:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
      description: Conflict with current state of the resource.
    InternalServerError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
      description: Something went wrong.
  schemas:
    Person:
      properties:
        email:
          example: newemail@gmail.com
          maxLength: 25
          minLength: 11
          type: string
        name:
          example: Mike
          maxLength: 20
          minLength: 2
          type: string
        surname:
          example: Anderson
          maxLength: 30
          minLength: 2
          type: string
      required:
      - email
      - name
      - surname
      type: object
    CreatePerson:
      example:
        password: 33password11
      properties:
        password:
          example: 33password11
          maxLength: 22
          minLength: 11
          type: string
      required:
      - password
      type: object
    ReadPerson:
      allOf:
      - $ref: '#/components/schemas/Person'
      example:
        id: 1
      properties:
        id:
          example: 1
          type: integer
      type: object
    ApiError:
      properties:
        response_code:
          example: 404
          type: integer
        error_message:
          example: example
          type: string
      type: object
