version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    networks:
      - my_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
  liquibase:
    image: liquibase/liquibase
    volumes:
      - ../src/main/resources/changelog:/liquibase/changelog
    command: --changeLogFile=master.xml --url=jdbc:postgresql://postgres:5432/postgres?autoReconnect=true&useSSL=false --username=postgres --password=password update
    depends_on:
      - postgres
    networks:
      - my_network
  api:
    image: api:1.0-SNAPSHOT
    restart: always
    environment:
        db.url: jdbc:postgresql://postgres:5432/postgres
        db.user: postgres
        db.password: password
        kafka.broker: kafka:9092
        kafka.topic: person
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - my_network
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - my_network
  kafka:
    image: 'wurstmeister/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: bridge
